In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import pandas as pd
import numpy as np
%matplotlib notebook

In [3]:
import pickle

In [6]:
pickle_in = open("analyses_AssayCandidates001_msd-data_d-arabitol_32_40A.msd.pkl","rb")
arabitol = pickle.load(pickle_in)
arabitol['data'][1]

array([0.02293191, 0.02322515, 0.02125541, ..., 0.02186867, 0.02341163,
       0.02225041], dtype=float32)

In [10]:
arabitol['data'][1][7000:].mean()

0.022905322

In [7]:
arabitol['means']

array([0.02292696, 0.04160443, 0.0598961 , 0.07810451, 0.09621306,
       0.11431306, 0.13244177, 0.15033455, 0.16840312, 0.18645836,
       0.20462655, 0.22229597, 0.24030991, 0.2584482 , 0.27627397,
       0.29436335, 0.31228736, 0.33017594, 0.3478957 , 0.36615798],
      dtype=float32)

In [8]:
arabitol

{'config': {'dtmax': 20,
  'selection': "atom.residue.name.startswith('HOH')",
  't0': 0,
  'tf': 10000},
 'data': {1: array([0.02293191, 0.02322515, 0.02125541, ..., 0.02186867, 0.02341163,
         0.02225041], dtype=float32),
  2: array([0.04205289, 0.03946011, 0.04207951, ..., 0.04250246, 0.04162379,
         0.04060601], dtype=float32),
  3: array([0.05890979, 0.06025792, 0.06027287, ..., 0.06048442, 0.06229789,
         0.05813787], dtype=float32),
  4: array([0.075887  , 0.07895144, 0.08057912, ..., 0.07980262, 0.08115853,
         0.07999542], dtype=float32),
  5: array([0.09308305, 0.09734682, 0.09813803, ..., 0.09511364, 0.0983422 ,
         0.10237523], dtype=float32),
  6: array([0.11153349, 0.11508821, 0.11325779, ..., 0.11226978, 0.11824021,
         0.11739582], dtype=float32),
  7: array([0.13126305, 0.13198137, 0.13522258, ..., 0.13182975, 0.12976566,
         0.13545142], dtype=float32),
  8: array([0.14930832, 0.15073498, 0.15601234, ..., 0.14856009, 0.14856721,
    

In [11]:
pickle_in = open("analyses_AssayCandidates001_msd-data_ribitol_32_40A.msd.pkl","rb")
ribitol = pickle.load(pickle_in)
ribitol['data'][1]

array([0.02242543, 0.02319271, 0.02383539, ..., 0.02240535, 0.02260947,
       0.02253287], dtype=float32)

In [19]:
ribitol['data'][1][7000:].mean()

0.022978123

In [12]:
ribitol['means']

array([0.02297639, 0.04174211, 0.06014241, 0.0784115 , 0.09658334,
       0.11472863, 0.13285492, 0.15098852, 0.1690611 , 0.18712988,
       0.2053257 , 0.2234217 , 0.24133596, 0.25930193, 0.27754688,
       0.2955129 , 0.31347144, 0.33156192, 0.34984425, 0.36778593],
      dtype=float32)

In [14]:
pickle_in = open("analyses_AssayCandidates001_msd-data_trehalose_32_40A.msd.pkl","rb")
trehalose = pickle.load(pickle_in)
trehalose['data'][1]

array([0.01977048, 0.02058203, 0.02024451, ..., 0.02156737, 0.02075462,
       0.0222258 ], dtype=float32)

In [16]:
trehalose['means']

array([0.0214088 , 0.03802685, 0.05418097, 0.07013711, 0.08605137,
       0.10183858, 0.11771752, 0.13334258, 0.1491653 , 0.16497956,
       0.18045977, 0.1961746 , 0.21184482, 0.22753009, 0.24325088,
       0.2587325 , 0.27418736, 0.29016793, 0.3052596 , 0.32117683],
      dtype=float32)

In [15]:
pickle_in = open("analyses_AssayCandidates001_msd-data_xylitol_32_40A.msd.pkl","rb")
xylitol = pickle.load(pickle_in)
xylitol['data'][1]

array([0.02313633, 0.0234328 , 0.02229499, ..., 0.02230005, 0.0229896 ,
       0.02419329], dtype=float32)

In [18]:
xylitol['data'][1][7000:].mean()

0.022889582

In [17]:
xylitol['means']

array([0.02290902, 0.04157051, 0.05986125, 0.07800526, 0.09616997,
       0.11420676, 0.13232344, 0.15026142, 0.16833031, 0.18632346,
       0.20424366, 0.2222119 , 0.24022628, 0.25813812, 0.27627498,
       0.29418358, 0.31205153, 0.3298556 , 0.3480539 , 0.36580223],
      dtype=float32)

In [20]:
pickle_in = open("analyses_AssayCandidates001_WOR_analysis_d-arabitol_32_40A.wor.pkl","rb")
arabitol_wor = pickle.load(pickle_in)
arabitol_wor['data'][1]

array([[0.3311468 , 0.34337556, 0.3362709 ],
       [0.3277378 , 0.32455724, 0.3390634 ],
       [0.3506468 , 0.35754925, 0.3579894 ],
       ...,
       [0.33446538, 0.3357889 , 0.3408713 ],
       [0.3341047 , 0.33995828, 0.3439299 ],
       [0.33076197, 0.33504543, 0.3458442 ]], dtype=float32)

In [21]:
pickle_in = open("analyses_AssayCandidates001_WOR_analysis_ribitol_32_40A.wor.pkl","rb")
ribitol_wor = pickle.load(pickle_in)
ribitol_wor['data'][1]

array([[0.32614303, 0.33849558, 0.3496758 ],
       [0.32718393, 0.33178207, 0.34083   ],
       [0.33337888, 0.35203645, 0.33842978],
       ...,
       [0.333573  , 0.33389714, 0.34783995],
       [0.32609236, 0.3371034 , 0.33361986],
       [0.33772835, 0.33999908, 0.35858646]], dtype=float32)

In [23]:
pickle_in = open("analyses_AssayCandidates001_WOR_analysis_xylitol_32_40A.wor.pkl","rb")
xylitol_wor = pickle.load(pickle_in)
xylitol_wor['data'][1]

array([[0.32270753, 0.3334857 , 0.34648737],
       [0.3265211 , 0.32835588, 0.33210042],
       [0.34115353, 0.36102304, 0.36421522],
       ...,
       [0.3387342 , 0.35125792, 0.34669703],
       [0.33273146, 0.34702086, 0.35501876],
       [0.3363237 , 0.33412543, 0.34324828]], dtype=float32)

In [26]:
arabitol_wor['means']

[array([0.3266431 , 0.33006384, 0.33864549]),
 array([0.16538096, 0.17319672, 0.17625899]),
 array([0.08844415, 0.09672873, 0.09770478]),
 array([0.04897484, 0.05643245, 0.05638122]),
 array([0.02780175, 0.03389548, 0.03383429]),
 array([0.01605773, 0.0211142 , 0.02081417]),
 array([0.00956452, 0.01386829, 0.01343559]),
 array([0.00570895, 0.00920035, 0.00915579]),
 array([0.00406791, 0.00652013, 0.00632886]),
 array([0.00230352, 0.00426177, 0.00407955])]

In [27]:
ribitol_wor['means']

[array([0.3253102 , 0.32876474, 0.33728579]),
 array([0.16395002, 0.17197868, 0.17487485]),
 array([0.08703633, 0.09556846, 0.09627743]),
 array([0.04780612, 0.05547387, 0.05562017]),
 array([0.02672622, 0.03310304, 0.032917  ]),
 array([0.01579217, 0.02040896, 0.01988092]),
 array([0.00978686, 0.01339032, 0.0128414 ]),
 array([0.00539689, 0.00859026, 0.0077716 ]),
 array([0.0034397 , 0.00584323, 0.005399  ]),
 array([0.00232304, 0.00424626, 0.003496  ])]

In [28]:
xylitol_wor['means']

[array([0.32690034, 0.33044318, 0.33880284]),
 array([0.16578075, 0.17379896, 0.17648012]),
 array([0.08866153, 0.09734751, 0.09779205]),
 array([0.04895037, 0.05656823, 0.05657731]),
 array([0.02763199, 0.03422637, 0.03404089]),
 array([0.01639459, 0.02144484, 0.02138866]),
 array([0.00968939, 0.01424499, 0.01363314]),
 array([0.00615501, 0.00980195, 0.00959298]),
 array([0.00418344, 0.00612193, 0.00576062]),
 array([0.00272932, 0.00505012, 0.00470718])]

In [29]:
arabitol_wor['data'][1][7000:].mean()

0.33196133

In [30]:
ribitol_wor['data'][1][7000:].mean()

0.33048517

In [31]:
xylitol_wor['data'][1][7000:].mean()

0.33219457

In [32]:
pickle_in = open("analyses_AssayCandidates001_WOR_analysis_trehalose_32_40A.wor.pkl","rb")
trehalose_wor = pickle.load(pickle_in)
trehalose_wor['data'][1]

array([[0.35266182, 0.35631195, 0.37966436],
       [0.35530022, 0.3528076 , 0.37166137],
       [0.37371308, 0.3702776 , 0.3765553 ],
       ...,
       [0.33602253, 0.33314756, 0.36257243],
       [0.347372  , 0.35458615, 0.3720908 ],
       [0.33589324, 0.346492  , 0.34423426]], dtype=float32)

In [33]:
trehalose_wor['means']

[array([0.34324007, 0.34676716, 0.35795961]),
 array([0.18519769, 0.19401372, 0.1997339 ]),
 array([0.10624265, 0.11644279, 0.11918238]),
 array([0.06413148, 0.0737169 , 0.07526377]),
 array([0.03973776, 0.04835054, 0.04948279]),
 array([0.02572995, 0.03340245, 0.03397721]),
 array([0.01716818, 0.02376322, 0.02395979]),
 array([0.01190001, 0.01777335, 0.01728913]),
 array([0.00835206, 0.01309399, 0.01374917]),
 array([0.0059533 , 0.00982542, 0.00976015])]

In [34]:
pickle_in = open("analyses_AssayCandidates001_WOR_analysis_d-mannitol_32_40A.wor.pkl","rb")
manitol_wor = pickle.load(pickle_in)
manitol_wor['data'][1]

array([[0.3384962 , 0.32856628, 0.35810038],
       [0.32508227, 0.33293656, 0.33573526],
       [0.32261884, 0.31596085, 0.32692584],
       ...,
       [0.31601346, 0.30888808, 0.3324429 ],
       [0.32166448, 0.32947502, 0.33126974],
       [0.32222223, 0.3242937 , 0.3431075 ]], dtype=float32)

In [35]:
manitol_wor['means']

[array([0.32905231, 0.3325775 , 0.34141423]),
 array([0.16832869, 0.17649473, 0.17987687]),
 array([0.09100233, 0.09964289, 0.10056478]),
 array([0.05093961, 0.05890294, 0.05900663]),
 array([0.02937771, 0.03613527, 0.03629585]),
 array([0.01748799, 0.02288984, 0.0227172 ]),
 array([0.01064427, 0.01518409, 0.01504343]),
 array([0.00687997, 0.0103077 , 0.00996814]),
 array([0.00410147, 0.00676885, 0.00706259]),
 array([0.0028019 , 0.0051739 , 0.00515617])]

In [36]:
pickle_in = open("analyses_AssayCandidates001_WOR_analysis_d-sorbitol_32_40A.wor.pkl","rb")
sorbitol_wor = pickle.load(pickle_in)
sorbitol_wor['data'][1]

array([[0.33341894, 0.34085175, 0.35205117],
       [0.32554796, 0.31957203, 0.34067214],
       [0.3243089 , 0.32958955, 0.3398058 ],
       ...,
       [0.31431213, 0.33341992, 0.33878714],
       [0.34256244, 0.3463296 , 0.34885687],
       [0.33089033, 0.32921425, 0.33952144]], dtype=float32)

In [37]:
sorbitol_wor['means']

[array([0.32927047, 0.33296671, 0.34172318]),
 array([0.16860813, 0.1768044 , 0.18002362]),
 array([0.09103116, 0.09995691, 0.10092106]),
 array([0.05118162, 0.05911268, 0.05910876]),
 array([0.02977608, 0.03611907, 0.03603571]),
 array([0.01748478, 0.02274151, 0.02281851]),
 array([0.01082561, 0.01529374, 0.01510475]),
 array([0.00685705, 0.01052833, 0.00993647]),
 array([0.00427873, 0.00720251, 0.00655902]),
 array([0.00365264, 0.0053242 , 0.00478669])]

In [38]:
pickle_in = open("analyses_AssayCandidates001_WOR_analysis_dulcitol_32_40A.wor.pkl","rb")
dulcitol_wor = pickle.load(pickle_in)
dulcitol_wor['data'][1]

array([[0.32733116, 0.33317629, 0.33985978],
       [0.32068488, 0.33618212, 0.3309523 ],
       [0.3336715 , 0.34014243, 0.34204474],
       ...,
       [0.34228954, 0.33970255, 0.34389904],
       [0.3192473 , 0.32946038, 0.33640444],
       [0.33335996, 0.33374822, 0.34939018]], dtype=float32)

In [39]:
dulcitol_wor['means']

[array([0.32908282, 0.33266778, 0.34145014]),
 array([0.16811314, 0.17628452, 0.17965479]),
 array([0.0908655 , 0.09935789, 0.10070064]),
 array([0.0512032 , 0.05876291, 0.05898538]),
 array([0.0294777 , 0.03560252, 0.0356668 ]),
 array([0.01787091, 0.02280419, 0.02250582]),
 array([0.01042037, 0.01484096, 0.01488945]),
 array([0.00684613, 0.01010377, 0.01004872]),
 array([0.00399946, 0.00692192, 0.00688377]),
 array([0.00303842, 0.00508769, 0.00510253])]

In [40]:
pickle_in = open("analyses_AssayCandidates001_msd-data_d-mannitol_32_40A.msd.pkl","rb")
manitol = pickle.load(pickle_in)
manitol['data'][1]

array([0.02321683, 0.02229955, 0.02325166, ..., 0.02347136, 0.02307759,
       0.02318695], dtype=float32)

In [41]:
pickle_in = open("analyses_AssayCandidates001_msd-data_d-sorbitol_32_40A.msd.pkl","rb")
sorbitol = pickle.load(pickle_in)
sorbitol['data'][1]

array([0.02266627, 0.02290609, 0.02348563, ..., 0.02349775, 0.02184195,
       0.02312504], dtype=float32)

In [42]:
pickle_in = open("analyses_AssayCandidates001_msd-data_dulcitol_32_40A.msd.pkl","rb")
dulcitol = pickle.load(pickle_in)
dulcitol['data'][1]

array([0.02331245, 0.02285592, 0.02253196, ..., 0.02300761, 0.02403562,
       0.02255383], dtype=float32)

In [43]:
manitol['means']

array([0.02267888, 0.04101464, 0.05898172, 0.07680582, 0.09458748,
       0.11225543, 0.12983821, 0.14756764, 0.1652206 , 0.1829415 ,
       0.20044687, 0.21808101, 0.23564105, 0.25314933, 0.27079424,
       0.28839818, 0.30571964, 0.3234702 , 0.34097204, 0.35871366],
      dtype=float32)

In [44]:
sorbitol['means']

array([0.02265066, 0.04094101, 0.05886825, 0.07659433, 0.09431675,
       0.11192925, 0.12959456, 0.14714615, 0.1648481 , 0.18222828,
       0.2000346 , 0.21733052, 0.2348188 , 0.25252104, 0.26995933,
       0.28782138, 0.30501157, 0.32277915, 0.3400276 , 0.3572981 ],
      dtype=float32)

In [45]:
dulcitol['means']

array([0.02266226, 0.04098741, 0.05894228, 0.07675365, 0.09447751,
       0.11222932, 0.12991522, 0.14755924, 0.16524386, 0.18284203,
       0.20063277, 0.21814652, 0.23581064, 0.2529489 , 0.27119708,
       0.28879976, 0.30592087, 0.32372883, 0.34128895, 0.35876003],
      dtype=float32)